name: test

on:
  push:
    branches:
    - master
  schedule:
    - cron: "* * 1 * *"

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
      - name: install dependencies
        run: sudo apt-get install libcurl4-openssl-dev
      - name: 'Get CIMMISS'
        run: Rscript -e 'source("code.R")'

      - name: Push to master
        uses: tcitry/push-to-master@v1.0
