name: get Anguilla_genus

on:
  push:
      branches: [ master ]
  #schedule:
  #  - cron: "0 2 * * *"

jobs:
  Anguilla_genus:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
      - name: install dependencies
        run: sudo apt-get install libcurl4-openssl-dev libgeos-dev libudunits2-dev
      - name: Install packages
        run: Rscript install.R
        
      - name: group1
        run: Rscript script1.R
      - name: push the result to GitHub
        run: |
          git config --local user.email ly_ding@126.com
          git config --local user.name Otoliths
          git add Anguilla_genus
          git commit Anguilla_genus --allow-empty -m 'add CIMMISS: ${{github.run_number}}' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.token}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
      
      - name: group2
        run: Rscript script2.R
      - name: push the result to GitHub
        run: |
          git config --local user.email ly_ding@126.com
          git config --local user.name Otoliths
          git add Anguilla_genus
          git commit Anguilla_genus --allow-empty -m 'add CIMMISS: ${{github.run_number}}' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.token}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
      
      - name: group3
        run: Rscript script3.R
      - name: push the result to GitHub
        run: |
          git config --local user.email ly_ding@126.com
          git config --local user.name Otoliths
          git add Anguilla_genus
          git commit Anguilla_genus --allow-empty -m 'add CIMMISS: ${{github.run_number}}' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.token}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"

      - name: group4
        run: Rscript script4.R
      - name: push the result to GitHub
        run: |
          git config --local user.email ly_ding@126.com
          git config --local user.name Otoliths
          git add Anguilla_genus
          git commit Anguilla_genus --allow-empty -m 'add CIMMISS: ${{github.run_number}}' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.token}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
