name: R-CMD-check

on:
  push:
    branches:
      - master
    schedule:
      - cron: '* * * * *'
  pull_request:
    branches:
      - master
    schedule:
      - cron: '* * * * *'

jobs:
  bot:
    runs-on: macOS-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
      - name: 'Get CIMMISS'
        run: Rscript -e 'source("code.R")'
      - name: 'Mirror to github'
        uses: pixta-dev/repository-mirroring-action@v1
        with:
        target_repo_url:
            git@github.com:Otoliths/CIMMISS.git
          ssh_private_key:
            ${{ secrets.CIMMISS }}
