name: R-CMD-check

on:
  push:
    branches:
      - master
    schedule:
      - cron: '* * * * *'
  pull_request:
    branches:
      - master
    schedule:
      - cron: '* * * * *'

jobs:
  bot:
    runs-on: macOS-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
      - name: 'Get CIMMISS'
        run: Rscript -e 'source("code.R")'
      - name: Upload COS
        uses: Otoliths/CIMMISS@master
        with:
           args: delete -r / && upload -r ./data//
           secretId: ${{CIMMISS}}
           secretKey: ${{12345678}}
           region: ap-shanghai
