name: get ynswj

on:
  schedule:
    - cron: "0 1/1 * * *"

jobs:
  ynswj:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
      - name: install dependencies
        run: sudo apt-get install libcurl4-openssl-dev libgeos-dev libudunits2-dev
      - name: Install packages
        run: Rscript install.R
        
      - name: water
        run: Rscript get_water.R
      - name: push the result to GitHub
        run: |
          git config --local user.email ly_ding@126.com
          git config --local user.name Otoliths
          git add water
          git commit water --allow-empty -m 'add CIMMISS: ${{github.run_number}}' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.token}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
      
      - name: rain
        run: Rscript get_rain.R
      - name: push the result to GitHub
        run: |
          git config --local user.email ly_ding@126.com
          git config --local user.name Otoliths
          git add rain
          git commit rain --allow-empty -m 'add CIMMISS: ${{github.run_number}}' || echo "No changes to commit"
          git push https://${{github.actor}}:${{secrets.token}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }} || echo "No changes to commit"
