name: R-CMD-check

on:
  push:
    branches:
      - master
    schedule:
      - cron: '*/1 * * * *'
  pull_request:
    branches:
      - master

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout codes'
        uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@master
          run: |
          Rscript -e "remotes::install_github('r-hub/sysreqs')"
          sysreqs=$(Rscript -e "cat(sysreqs::sysreq_commands('DESCRIPTION'))")
          sudo -s eval "$sysreqs"
      - name: 'Get CIMMISS'
        run: bash ./code.sh
